# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/gw_analysis_tools

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/gw_analysis_tools

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/gw_analysis_tools/CMakeFiles /opt/gw_analysis_tools//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /opt/gw_analysis_tools/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /opt/gw_analysis_tools/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gwat_static

# Build rule for target.
gwat_static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gwat_static
.PHONY : gwat_static

# fast build rule for target.
gwat_static/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/gwat_static.dir/build.make src/CMakeFiles/gwat_static.dir/build
.PHONY : gwat_static/fast

#=============================================================================
# Target rules for targets named gwat

# Build rule for target.
gwat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gwat
.PHONY : gwat

# fast build rule for target.
gwat/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/gwat.dir/build.make src/CMakeFiles/gwat.dir/build
.PHONY : gwat/fast

#=============================================================================
# Target rules for targets named OBJS

# Build rule for target.
OBJS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 OBJS
.PHONY : OBJS

# fast build rule for target.
OBJS/fast:
	$(MAKE) $(MAKESILENT) -f src/CMakeFiles/OBJS.dir/build.make src/CMakeFiles/OBJS.dir/build
.PHONY : OBJS/fast

#=============================================================================
# Target rules for targets named autocorr_tool

# Build rule for target.
autocorr_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 autocorr_tool
.PHONY : autocorr_tool

# fast build rule for target.
autocorr_tool/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/autocorr_tool.dir/build.make apps/CMakeFiles/autocorr_tool.dir/build
.PHONY : autocorr_tool/fast

#=============================================================================
# Target rules for targets named fisher_tool

# Build rule for target.
fisher_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fisher_tool
.PHONY : fisher_tool

# fast build rule for target.
fisher_tool/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/fisher_tool.dir/build.make apps/CMakeFiles/fisher_tool.dir/build
.PHONY : fisher_tool/fast

#=============================================================================
# Target rules for targets named rjmcmc_gw_tool_2wf

# Build rule for target.
rjmcmc_gw_tool_2wf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rjmcmc_gw_tool_2wf
.PHONY : rjmcmc_gw_tool_2wf

# fast build rule for target.
rjmcmc_gw_tool_2wf/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/rjmcmc_gw_tool_2wf.dir/build.make apps/CMakeFiles/rjmcmc_gw_tool_2wf.dir/build
.PHONY : rjmcmc_gw_tool_2wf/fast

#=============================================================================
# Target rules for targets named mcmc_gw_tool_v2

# Build rule for target.
mcmc_gw_tool_v2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcmc_gw_tool_v2
.PHONY : mcmc_gw_tool_v2

# fast build rule for target.
mcmc_gw_tool_v2/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/mcmc_gw_tool_v2.dir/build.make apps/CMakeFiles/mcmc_gw_tool_v2.dir/build
.PHONY : mcmc_gw_tool_v2/fast

#=============================================================================
# Target rules for targets named mcmc_gw_tool

# Build rule for target.
mcmc_gw_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mcmc_gw_tool
.PHONY : mcmc_gw_tool

# fast build rule for target.
mcmc_gw_tool/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/mcmc_gw_tool.dir/build.make apps/CMakeFiles/mcmc_gw_tool.dir/build
.PHONY : mcmc_gw_tool/fast

#=============================================================================
# Target rules for targets named create_gw_init_file

# Build rule for target.
create_gw_init_file: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 create_gw_init_file
.PHONY : create_gw_init_file

# fast build rule for target.
create_gw_init_file/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/create_gw_init_file.dir/build.make apps/CMakeFiles/create_gw_init_file.dir/build
.PHONY : create_gw_init_file/fast

#=============================================================================
# Target rules for targets named waveform_tool

# Build rule for target.
waveform_tool: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 waveform_tool
.PHONY : waveform_tool

# fast build rule for target.
waveform_tool/fast:
	$(MAKE) $(MAKESILENT) -f apps/CMakeFiles/waveform_tool.dir/build.make apps/CMakeFiles/waveform_tool.dir/build
.PHONY : waveform_tool/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... OBJS"
	@echo "... autocorr_tool"
	@echo "... create_gw_init_file"
	@echo "... fisher_tool"
	@echo "... gwat"
	@echo "... gwat_static"
	@echo "... mcmc_gw_tool"
	@echo "... mcmc_gw_tool_v2"
	@echo "... rjmcmc_gw_tool_2wf"
	@echo "... waveform_tool"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /opt/gw_analysis_tools/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

